#!/system/bin/sh
#added init.d support
export PATH=${PATH}:/system/bin:/system/xbin
mount -o remount,rw -t auto /system
chmod -R 755 /system/etc/init.d
mount -o remount,ro -t auto /system
logwrapper busybox run-parts /system/etc/init.d/
